export const SIGNIN_ISLOADING = 'SIGNIN_ISLOADING';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE';

export const SIGNUP_ISLOADING = 'SIGNUP_ISLOADING';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const FORGOT_PASSWORD_ISLOADING = 'FORGOT_PASSWORD_ISLOADING';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE';

export const CLEAR_STATE = 'CLEAR_STATE';
export const CLEAR_MESSAGES = 'CLEAR_MESSAGES';

export const SET_TOKEN = 'SET_TOKEN';
