export const FETCH_CHATS_SUCCESS = 'FETCH_CHATS_SUCCESS';
export const FETCH_CHATS_FAILURE = 'FETCH_CHATS_FAILURE';
export const FETCH_CHATS_ISLOADING = 'FETCH_CHATS_ISLOADING';

export const FETCH_CONVERSATIONS_SUCCESS = 'FETCH_CONVERSATIONS_SUCCESS';
export const FETCH_CONVERSATIONS_FAILURE = 'FETCH_CONVERSATIONS_FAILURE';
export const FETCH_CONVERSATIONS_ISLOADING = 'FETCH_CONVERSATIONS_ISLOADING';

export const CREATE_CONVERSATIONS_SUCCESS = 'CREATE_CONVERSATIONS_SUCCESS';
export const CREATE_CONVERSATIONS_FAILURE = 'CREATE_CONVERSATIONS_FAILURE';
export const CREATE_CONVERSATIONS_ISLOADING = 'CREATE_CONVERSATIONS_ISLOADING';