export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE';
export const FETCH_POSTS_ISLOADING = 'FETCH_POSTS_ISLOADING';

export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';
export const FETCH_POST_FAILURE = 'FETCH_POST_FAILURE';
export const FETCH_POST_ISLOADING = 'FETCH_POST_ISLOADING';

export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_FAILURE = 'DELETE_POST_FAILURE';
export const DELETE_POST_ISLOADING = 'DELETE_POST_ISLOADING';

export const ADD_POST_CONTENT_SUCCESS = 'ADD_POST_CONTENT_SUCCESS';
export const ADD_POST_CONTENT_FAILURE = 'ADD_POST_CONTENT_FAILURE';
export const ADD_POST_CONTENT_ISLOADING = 'ADD_POST_CONTENT_ISLOADING';

export const CLEAR_POST_MESSAGE = 'CLEAR_POST_MESSAGE';

export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_FAILURE = 'ADD_COMMENT_FAILURE';
export const ADD_COMMENT_ISLOADING = 'ADD_COMMENT_ISLOADING';

export const FETCH_CURRENT_USER_POSTS_SUCCESS = 'FETCH_CURRENT_USER_POSTS_SUCCESS';
export const FETCH_CURRENT_USER_POSTS_FAILURE = 'FETCH_CURRENT_USER_POSTS_FAILURE';
export const FETCH_CURRENT_USER_POSTS_ISLOADING = 'FETCH_CURRENT_USER_POSTS_ISLOADING';

export const FETCH_USER_POSTS_SUCCESS = 'FETCH_USER_POSTS_SUCCESS';
export const FETCH_USER_POSTS_FAILURE = 'FETCH_USER_POSTS_FAILURE';
export const FETCH_USER_POSTS_ISLOADING = 'FETCH_USER_POSTS_ISLOADING';