export const FETCH_MY_PROFILE_SUCCESS = 'FETCH_MY_PROFILE_SUCCESS';
export const FETCH_MY_PROFILE_FAILURE = 'FETCH_MY_PROFILE_FAILURE';
export const MYPROFILE_ISLOADING = 'MYPROFILE_ISLOADING';

export const UPDATE_INFO_ISLOADING = 'UPDATE_INFO_ISLOADING';
export const UPDATE_INFO_SUCCESS = 'UPDATE_INFO_SUCCESS';
export const UPDATE_INFO_FAILURE = 'UPDATE_INFO_FAILURE';

export const UPDATE_EMAIL_ISLOADING = 'UPDATE_EMAIL_ISLOADING';
export const UPDATE_EMAIL_SUCCESS = 'UPDATE_EMAIL_SUCCESS';
export const UPDATE_EMAIL_FAILURE = 'UPDATE_EMAIL_FAILURE';

export const UPDATE_PASSWORD_ISLOADING = 'UPDATE_PASSWORD_ISLOADING';
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS';
export const UPDATE_PASSWORD_FAILURE = 'UPDATE_PASSWORD_FAILURE';

export const CLEAR_PROFILE_MSGS = 'CLEAR_PROFILE_MSGS';

export const UPLOAD_PROFILE_IMAGE_ISLOADING = 'UPLOAD_PROFILE_IMAGE_ISLOADING';
export const UPLOAD_PROFILE_IMAGE_SUCCESS = 'UPLOAD_PROFILE_IMAGE_SUCCESS';
export const UPLOAD_PROFILE_IMAGE_FAILURE = 'UPLOAD_PROFILE_IMAGE_FAILURE';

export const UPLOAD_COVER_IMAGE_ISLOADING = 'UPLOAD_COVER_IMAGE_ISLOADING';
export const UPLOAD_COVER_IMAGE_SUCCESS = 'UPLOAD_COVER_IMAGE_SUCCESS';
export const UPLOAD_COVER_IMAGE_FAILURE = 'UPLOAD_COVER_IMAGE_FAILURE';
