export const FETCH_USER_ISLOADING = 'FETCH_USER_ISLOADING';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';

export const FETCH_USERS_ISLOADING = 'FETCH_USERS_ISLOADING';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';

export const FETCH_FRIENDS_ISLOADING = 'FETCH_FRIENDS_ISLOADING';
export const FETCH_FRIENDS_SUCCESS = 'FETCH_FRIENDS_SUCCESS';
export const FETCH_FRIENDS_FAILURE = 'FETCH_FRIENDS_FAILURE';

export const FETCH_FOLLOWINGS_ISLOADING = 'FETCH_FOLLOWINGS_ISLOADING';
export const FETCH_FOLLOWINGS_SUCCESS = 'FETCH_FOLLOWINGS_SUCCESS';
export const FETCH_FOLLOWINGS_FAILURE = 'FETCH_FOLLOWINGS_FAILURE';

export const FOLLOW_USER_ISLOADING = 'FOLLOW_USER_ISLOADING';
export const FOLLOW_USER_SUCCESS = 'FOLLOW_USER_SUCCESS';
export const FOLLOW_USER_FAILURE = 'FOLLOW_USER_FAILURE';

export const UNFOLLOW_USER_ISLOADING = 'UNFOLLOW_USER_ISLOADING';
export const UNFOLLOW_USER_SUCCESS = 'UNFOLLOW_USER_SUCCESS';
export const UNFOLLOW_USER_FAILURE = 'UNFOLLOW_USER_FAILURE';